RU_LABEL = "RU"
EN_LABEL = "EN"

RU_DS_LABEL = "RU"
EN_DS_LABEL = "EN"

EOS_LABEL = "<EOS>"
SOS_LABEL = "<SOS>"

WORD_PUNCT_TOKENIZER_WITH_SOS = "wpt"
WORD_PUNCT_TOKENIZER_WITHOUT_SOS = "ru_tok"

AMOUNT_OF_SAMPLES = 200000
BATCH_SIZE = 50

BASE_PATH = "."
FAST_TEXT_VECTOR_SIZE = 300