RU_LABEL = "RU"
EN_LABEL = "EN"

RU_DS_LABEL = "RU"
EN_DS_LABEL = "EN"

EOS_LABEL = "<EOS>"
SOS_LABEL = "<SOS>"

WORD_PUNCT_TOKENIZER_WITH_SOS = "wpt"
WORD_PUNCT_TOKENIZER_WITHOUT_SOS = "ru_tok"

STOP_COMMAND_KEY = "stop"
SAVE_EACH_N_EPOCH = "save_each_n_epoch"

AMOUNT_OF_SAMPLES = 200000
BATCH_SIZE = 50
CONTINUE_LEARNING = True
EPOCH_NUMBER = 100

BASE_PATH = "."
FAST_TEXT_VECTOR_SIZE = 300

EPOCH = 'epoch'
ENCODER_STATE_DICT = 'encoder_state_dict'
DECODER_STATE_DICT = 'decoder_state_dict'
ENCODER_OPTIMIZER_STATE_DICT = 'encoder_optimizer_state_dict'
DECODER_OPTIMIZER_STATE_DICT = 'decoder_optimizer_state_dict'
THE_LOWEST_LOSS = "the_lowest_loss"

MAX_ENGLISH_SEQUENCE_LEN = 47
MAX_RUSSIAN_SEQUENCE_LEN = 41
